DACT-258: adding in some more tests about date validation.
companieshouse/officer-filing-api pull request #31
Opened 2022-11-28 15:18 UTC by rwalrondch

2022-12-01 11:08 UTC, jditchburn requested changes

2022-12-01 14:32 UTC, rwalrondch commented on src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java
> +        String formattedDate = new SimpleDateFormat("yyyy-MMM-dd").format(Date.from(Instant.now()));
Yes, it is to test with the date being NOV rather than 11,  and the format for that is 3 M's

2022-12-01 14:34 UTC, rwalrondch commented on src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java
> +    void createFilingWhenResignedOnDateTodayOKThenResponse201() throws Exception {
It's a thought,  but whereas we have 5 or 6 different formats for failing tests,  there are only 2 I believe for passing tests,  in the past and today.

2022-12-01 14:35 UTC, rwalrondch commented on src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java
> +    private void Response400BaseTest(String replacementString) throws Exception {
Yes, good spot.

2022-12-01 14:47 UTC, rwalrondch commented on src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java
> +        String formattedDate = new SimpleDateFormat("dd-MMM-yyyy").format(Date.from(Instant.now()));
oops, good spot, should only be 2 here.

2022-12-01 14:47 UTC, rwalrondch commented on src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java
> +    }
Yes, I have altered them.

2022-12-01 15:41 UTC, jditchburn approved these changes

2022-12-06 11:41 UTC, tracetechnical commented
Hi All,
Just to let you know, this would deploy to tcats-1 at the moment, which I am trying to fix, but am waiting on permissions.
You may have to let Thundercats know if you merge this before we switch to reserve-2

2022-12-07 10:22 UTC, jbestwickch approved these changes

2022-12-07 14:35 UTC, merged