DACT-242 Validate termination date before appointment date
companieshouse/officer-filing-api pull request #40
Opened 2023-01-10 14:30 UTC by jditchburn

2023-01-11 08:23 UTC, AlisonGriffiths requested changes
The code looks great, can you check whether there is a scenario missing here. 
I believe that if is_pre_1992_appointment = true then you won't have an appointed_on date you will have an appointed_before date.

I have a feeling you need to include the pre 1992 appointment scenario to complete the validation.

2023-01-11 09:25 UTC, AlisonGriffiths commented
Having discussed the pre 1992 appointment scenario with Richard, any resignation pre dating that won't be sent through on the TM01 form. 
So it is just the minor code smell flagged up by sonar left

2023-01-11 15:25 UTC, rwalrondch approved these changes

2023-01-11 16:13 UTC, AlisonGriffiths approved these changes

2023-01-13 14:52 UTC, jditchburn commented
Latest commit was just to fix minor code conflicts

2023-01-13 14:52 UTC, merged